In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
b=np.array([1,2,3,4,5,10,9,8,7,6])

In [3]:
a==b

array([ True,  True,  True,  True,  True, False, False,  True, False,
       False])

In [4]:
a<b

array([False, False, False, False, False,  True,  True, False, False,
       False])

In [5]:
a>b

array([False, False, False, False, False, False, False, False,  True,
        True])

matrix multiplication: ([[1,2,3][4,5,6]])*([[1,2,3][4,5,6]])=([[1*1,2*2,3*3],[4*4,5*5,6*6]])

In [9]:
c=np.array([[1,2,3],[4,5,6]])
d=c
c*d

array([[ 1,  4,  9],
       [16, 25, 36]])

In [11]:
c+d

array([[ 2,  4,  6],
       [ 8, 10, 12]])